@echo off
echo Starting HUM Fleet Backend Server...
start cmd /k "cd server && node index.js"

echo Starting HUM Fleet Admin Panel...
start cmd /k "cd admin-cms && npm run dev"

echo Waiting for servers to start...
timeout /t 3 /nobreak > nul

echo Opening Admin Panel in your browser...
start http://localhost:5173
